### ISSUE TITLE
Pbm dans 2.1.1

### ISSUE THREAD

**Issue by pierr0t** [thelia-modules/FreeShipping#7]
Bonjour,
Pour d'autres soucis j'ai passé mon installation locale en 2.1.1 depuis la 2.0.4 et j'ai donc installé la branche master de FreeShipping et je rencontre 2-3 soucis.
Tout d'abord, quel que soit le seuil déclaré, le port est en franco sur la page cart (estimation du transport quand le client n'est pas signé). Si je dévalide le plugin, j'ai les bons tarifs colissimo.
Ensuite si le client se signe, ça redevient bon sur l'écran delivery, Colissimo ré-apparait coché, avec Franco de port non coché en dessous (mais à mon avis, franco devrait disparaitre sinon tout le monde va le cocher non ?) Je dois traiter ça au niveau de la template ?
Et dans le back-office, si je crée plusieurs seuils pour plusieurs zones, impossible ensuite de les détruire, quand je clique sur la poubelle, retour direct dans l'espace public sans suppression du seuil.
Pierre.

**Comment by pierr0t** [comment]
Un petit up sur ce pbm, j'ai passé mon site de prod en 2.1.1, même problème, inutilisable pour moi.
Merci !

**Comment by mespeche** [comment]
Bonjour pierr0t,

Je m'en occupe au plus vite.

Merci.

**Comment by mespeche** [comment]
Je viens de mettre à disposition une version toute neuve disponible dans la liste des releases : 
[Tag v1.0.1](https://github.com/thelia-modules/FreeShipping/releases/tag/v1.0.1)

Tout est automatique mis à par l'étape de sélection du mode de transport en étape 2 qui est à gérer au niveau du template en proposant les autres types de transport si FreeShipping n'est pas utilisé. (Avec une boucle de type delivery qui prend en ID celui du module).

**Comment by pierr0t** [comment]
Mes premiers tests semblent bon bon bon :-)
Merci !!
Pierre
