### ISSUE TITLE
Problèmes de droits

### ISSUE THREAD

**Issue by pierr0t** [thelia-modules/FreeShipping#8]
Bonjour,

L'utilisateur du site a un profil créé spécifiquement avec un peu moins de droits que le super-admin. Je lui ai donné les droits pour par ex modifier le montant du franco de port et ça ne fonctionne pas ... dès qu'on clique sur "modifier", on a un oops ... Pourtant j'ai mis tous les curseurs au vert ...

Pierre.

**Comment by pierr0t** [comment]
J'ai de nouveau diagnostiqué ça depuis 0 (j'avais carrément oublié ce ticket) ... donc je confirme que ça ne marche pas :-)

**Comment by mespeche** [comment]
Il me faudrait un peu plus d'informations pour que je puisse recréer le problème de mon côté. Quels sont les droits assignés à ce profil ?

**Comment by pierr0t** [comment]
Concernant le module Freeshipping, tous. Après au niveau de tous les autres réglages, la liste est très longue, y-a-t-il un moyen de vous faire passer tout ça sous forme textuelle par ex ?

**Comment by mespeche** [comment]
Une capture d'écran au niveau des droits du profil par exemple pourrait être bien.

**Comment by pierr0t** [comment]
Voici en plusieurs écrans.

![capture d ecran 2015-03-30 a 15 43 08 30](https://cloud.githubusercontent.com/assets/1298608/6897391/b1544626-d6f3-11e4-8495-292eefec3729.png)
![capture d ecran 2015-03-30 a 15 43 31 30](https://cloud.githubusercontent.com/assets/1298608/6897399/bf5ce9e4-d6f3-11e4-91ff-6a64e834b4f9.png)
![capture d ecran 2015-03-30 a 15 43 51 30](https://cloud.githubusercontent.com/assets/1298608/6897400/c2703410-d6f3-11e4-84c1-26a93b50a983.png)
![capture d ecran 2015-03-30 a 15 44 01 30](https://cloud.githubusercontent.com/assets/1298608/6897401/c4c2ebae-d6f3-11e4-9377-433655388328.png)

**Comment by mespeche** [comment]
Voilà c'est résolu !

Merci pour tes retours.

**Comment by pierr0t** [comment]
Nickel, ça marche ! merci !
